all:
	echo "Задание часть 1 - Разделяемая память"
	gcc sender.c -o sender
	gcc receiver.c -o receiver
	./sender
	//echo "Задание часть 2 - Потоки"
	//gcc threader.c -lpthread -o threader
	//./threader
